#############################################################################
# Generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#  Jun 24, 2020 04:14:25 AM EDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 10 -menu "$top.m44" -background #d83253 -cursor arrow 
    wm focusmodel $top passive
    wm geometry $top 748x487
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Password Manager"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0 add command \
        -activebackground #6700ed -activeforeground #000000 -accelerator {} \
        -background #d5bad8 -command {{}} -compound left \
        -font "-family Lato -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(pr,menufgcolor) -hidemargin 1 -label Encoder 
    $site_3_0 add command \
        -activebackground #00dded -activeforeground #000000 -accelerator {} \
        -background $vTcl(pr,menubgcolor) -command {{}} -compound left \
        -font "-family Lato -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(pr,menufgcolor) -hidemargin 0 -label Decoder 
    $site_3_0 add checkbutton \
        -variable checks_2 -activebackground #5e5e5e \
        -activeforeground #000000 -accelerator {} \
        -background $vTcl(pr,menubgcolor) -command {{}} -compound left \
        -font "-family Lato -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(pr,menufgcolor) -hidemargin 0 -label {Dark Theme} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men45" -activebackground #ed0552 \
        -activeforeground #000000 -accelerator {} \
        -background $vTcl(pr,menubgcolor) -command {{}} -compound center \
        -font "-family MathJax_Main -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground $vTcl(pr,menufgcolor) -hidemargin 0 -label Exit 
    menu $site_3_0.men45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont -foreground black \
        -tearoff 0 
    $site_3_0 add separator \
        -background $vTcl(pr,menubgcolor) 
    entry $top.ent46 \
        -background #36d7ff -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 256 
    vTcl:DefineAlias "$top.ent46" "email" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background #12d7ff -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 256 
    vTcl:DefineAlias "$top.ent49" "website" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background #03e6ff -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 256 
    vTcl:DefineAlias "$top.ent50" "password" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -background #d83253 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor #efeded -takefocus 1 \
        -text {Enter Your Email Or Name} 
    vTcl:DefineAlias "$top.lab51" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #d83253 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Enter Your Website} 
    vTcl:DefineAlias "$top.lab52" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -background #d83253 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text {Enter Your Password} 
    vTcl:DefineAlias "$top.lab53" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa55 \
        -background #d80606 -foreground $vTcl(actual_gui_fg) \
        -font TkDefaultFont -relief flat -anchor w -justify left \
        -text {This Software Made By FahadAkash} -cursor spider 
    vTcl:DefineAlias "$top.tLa55" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -background #d8b91c -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Click Here} 
    vTcl:DefineAlias "$top.but56" "MainButton" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che57 \
        -background #d83253 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -justify left \
        -text {Check For Term And Condition} -variable che57 
    vTcl:DefineAlias "$top.che57" "termcheck" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo60 \
        -width 302 -height 136 -takefocus {} 
    vTcl:DefineAlias "$top.tNo60" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo60.t0 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo60.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo60 add $top.tNo60.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo60.t0
    frame $top.tNo60.t1 \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo60.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo60 add $top.tNo60.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo60.t1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.ent46 \
        -in $top -x 0 -relx 0.393 -y 0 -rely 0.156 -width 256 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 0 -relx 0.393 -y 0 -rely 0.267 -width 256 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 0 -relx 0.393 -y 0 -rely 0.378 -width 256 -relwidth 0 \
        -height 33 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.12 -y 0 -rely 0.164 -width 0 -relwidth 0.255 \
        -height 0 -relheight 0.07 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.122 -y 0 -rely 0.267 -width 0 -relwidth 0.255 \
        -height 0 -relheight 0.07 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.12 -y 0 -rely 0.37 -width 0 -relwidth 0.255 \
        -height 0 -relheight 0.07 -anchor nw -bordermode ignore 
    place $top.tLa55 \
        -in $top -x 0 -y 0 -rely 0.912 -width 0 -relwidth 0.397 -height 0 \
        -relheight 0.131 -anchor nw -bordermode ignore 
    place $top.but56 \
        -in $top -x 0 -relx 0.468 -y 0 -rely 0.575 -width 131 -relwidth 0 \
        -height 51 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che57 \
        -in $top -x 0 -relx 0.401 -y 0 -rely 0.472 -width 0 -relwidth 0.33 \
        -height 0 -relheight 0.068 -anchor nw -bordermode ignore 
    place $top.tNo60 \
        -in $top -x 0 -relx 0.575 -y 0 -rely 0.698 -width 0 -relwidth 0.404 \
        -height 0 -relheight 0.279 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

